inherit_gem:
  rubocop-standard:
    - config/default.yml
    - config/minitest.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - "pkg/**/*"
    - "ext/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "test/progit/**/*"
